builds:
  - binary: migration
    main: cmd/migration/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  github:
    owner: gosidekick
    name: migration
